name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Replace with the desired distribution
          java-version: '22'   # Replace with the specific version
          cache: 'maven'
      - name: Check Maven Version
        run: mvn -v
      - name: Build and Test
        run: >
          xvfb-run
          mvn -B verify -Djavafx.platform=linux
          jacoco:report
          -Pcoverage
      - name: Get JaCoCo Coverage
        id: coverage  
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=13.43
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved."
            exit 1
          else
            echo "New coverage: $coverage%"
          fi
